### ISSUE TITLE
Reason behind not running discriminator extra iterations during initial training levels 

### ISSUE THREAD

**Issue by prannayk** [jiamings/wgan#4]
I believe, they run their discriminators extra iterations during initial training. Is there more stability in gradient clipping methods that we don't do this? Or is it actually not better to do this in this case?

**Comment by jiamings** [comment]
I think I did run more iterations in the original WGAN implementation - [line 54](https://github.com/jiamings/wgan/blob/master/wgan.py#L54). 
I did not do that in the gradient penalty case, since I didn't find it to be necessary (empirically).

**Comment by prannayk** [comment]
Thanks a lot.
