### ISSUE TITLE
Wrong objective

### ISSUE THREAD

**Issue by bernhard2202** [jiamings/wgan#5]
https://github.com/jiamings/wgan/blob/e46cae12dc01d52c3480bb90711607aefc682e1e/wgan_v2.py#L29

I think according to the paper there is a minus missing in this line. the paper is optimising -D(G(z))

**Comment by jiamings** [comment]
Depends on how you treat D - give large values to real samples for give large values to fake samples. So long as this is consistent, the code will work.
